<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = $this->zoneconfig['conf']['id'];
    $data_melisKey = $this->melisKey;
?>

<div id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>" class="tab-pane container-level-a">
    <div class="me-heading bg-white border-bottom" id="id_melis_site_translation_tool_header" data-meliskey="melis_site_translation_tool_header">
        <div class="row">
            <div class="me-hl col-xs-12 col-sm-8 col-md-9">
                <h1 class="content-heading"><?= $this->translate('tr_melis_site_translation_name')?></h1>
                <p><?= $this->translate('tr_melis_site_translation_name_description')?></p>
            </div>
            <div class="me-hr col-xs-12 col-sm-4 col-md-3">
                <div class="mst-btn-add">
                    <a href="javascript:void(0)" class="btn btn-success btnAddSiteTranslation" data-meliskey=""><i class="fa fa-plus"></i> <?= $this->translate('tr_melis_site_translation_add_translation')?></a>
                </div>
            </div>
        </div>
    </div>
    <div class="spacing-x2 innerAll">
        <?= $this->melis_site_translation_tool_content; ?>
    </div>
</div>