<?php
$name = '';
$id = '';
if (!empty($this->zoneconfig['conf']['name']))
    $name = $this->zoneconfig['conf']['name'];
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
$data_melisKey = $this->melisKey;

?>
<div id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>">
    <div class="modal-content">
        <div class="modal-body padding-none">
            <div class="wizard">
                <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                    <div class="widget-head">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#" class="glyphicons plus" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate('tr_melis_site_translation_add_translation') ?></a></li>
                        </ul>
                    </div>
                    <div class="widget-body innerAll inner-2x">
                        <div class="tab-content">
                            <div class="tab-pane active" <?php echo $id ?>>
                                <?php
                                    $form = $this->melissitetranslation_form;
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    echo $this->melisFieldCollection($form);
                                    echo $this->form()->closeTag();
                                ?>
                                <div align="right">
                                    <a data-dismiss="modal" class="btn btn-danger pull-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_melis_site_translation_close_btn')?></a>
                                    <a class="btn btn-success btnSaveSiteTranslation"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_melis_site_translation_save_btn'); ?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            //we prepare the tinyMce init here to make sure that the form are already loaded
            melisTinyMCE.createTinyMCE("tool", "textarea#mstt_text", {
                toolbar : 'undo redo | styleselect | bold italic | alignleft aligncenter alignright'
            });
        });
    </script>
</div>
